//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION
    {
        public ATENCION()
        {
            this.RECAUDACION = new HashSet<RECAUDACION>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ATE_ID { get; set; }
        public decimal TIPO_PAGO_TPA_ID { get; set; }
        public decimal FORMA_PAGO_FPA_ID { get; set; }
        public decimal CAJA_CAJ_ID { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
        public virtual ICollection<RECAUDACION> RECAUDACION { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
