//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_MEDICO
    {
        public CENTRO_MEDICO()
        {
            this.MEDICO = new HashSet<MEDICO>();
        }
    
        public decimal CME_ID { get; set; }
        public string CME_NOMBRE { get; set; }
        public string CME_DIRECCION { get; set; }
        public string CME_EMAIL { get; set; }
        public decimal CME_TELEFONO { get; set; }
        public System.DateTime CME_HORA_APERT { get; set; }
        public System.DateTime CME_HORA_CIERRE { get; set; }
    
        public virtual ICollection<MEDICO> MEDICO { get; set; }
    }
}
