//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORES
    {
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TABLA { get; set; }
        public string CODIGO_ERROR { get; set; }
        public string DETALLE { get; set; }
    }
}
