//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_RESERVA
    {
        public decimal ID { get; set; }
        public string FECHA { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_USUARIO { get; set; }
        public decimal ID_RESERVA { get; set; }
    }
}
