//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.HORARIO = new HashSet<HORARIO>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal MED_ID { get; set; }
        public string MED_NOMBRES { get; set; }
        public string MED_PATERNO { get; set; }
        public string MED_MATERNO { get; set; }
        public decimal CENTRO_MEDICO_CME_ID { get; set; }
        public decimal ESPECIALIDAD_ESP_ID { get; set; }
        public decimal MED_MIN_AT { get; set; }
        public decimal MED_VALOR_AT { get; set; }
        public decimal USUARIO_USU_ID { get; set; }
    
        public virtual CENTRO_MEDICO CENTRO_MEDICO { get; set; }
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
