//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        public decimal PER_ID { get; set; }
        public decimal RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRES { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public System.DateTime FNAC { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> CELULAR { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public decimal ESTADO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public decimal USUARIO_USU_ID { get; set; }
    
        public virtual CAJERO CAJERO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual SECRETARIA SECRETARIA { get; set; }
    }
}
