//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECAUDACION
    {
        public decimal REC_ID { get; set; }
        public decimal ATENCION_ATE_ID { get; set; }
        public decimal REC_PORCENTAJE { get; set; }
        public decimal REC_TOTAL { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
    }
}
