//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal RES_ID { get; set; }
        public System.DateTime RES_FECHA { get; set; }
        public System.DateTime RES_HORA_INICIO { get; set; }
        public System.DateTime RES_HORA_TERM { get; set; }
        public decimal MEDICO_MED_ID { get; set; }
        public decimal PACIENTE_PAC_ID { get; set; }
        public decimal TIPO_RESERVA_TRE_ID { get; set; }
        public decimal RES_ESTADO { get; set; }
        public decimal ATENCION_ATE_ID { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual TIPO_RESERVA TIPO_RESERVA { get; set; }
    }
}
