//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.MEDICO = new HashSet<MEDICO>();
            this.PACIENTE = new HashSet<PACIENTE>();
            this.PERSONAL = new HashSet<PERSONAL>();
        }
    
        public decimal USU_ID { get; set; }
        public string USU_USERNAME { get; set; }
        public string USU_PASS { get; set; }
        public string USU_ULTIMOPASS { get; set; }
        public System.DateTime USU_FREGISTRO { get; set; }
        public decimal USU_ESTADO { get; set; }
        public Nullable<decimal> TIPO_USUARIO_TU_ID { get; set; }
        public string USU_EMAIL { get; set; }
    
        public virtual ICollection<MEDICO> MEDICO { get; set; }
        public virtual ICollection<PACIENTE> PACIENTE { get; set; }
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
