-- ESPECIALIDAD

INSERT INTO ESPECIALIDAD (ESP_ID, ESP_NOMBRE) VALUES (1,'CARDIOLOGÍA');
INSERT INTO ESPECIALIDAD (ESP_ID, ESP_NOMBRE) VALUES (2,'DENTISTA');
INSERT INTO ESPECIALIDAD (ESP_ID, ESP_NOMBRE) VALUES (3,'MEDICINA GENERAL');
INSERT INTO ESPECIALIDAD (ESP_ID, ESP_NOMBRE) VALUES (4,'NUTRICIÓN');
INSERT INTO ESPECIALIDAD (ESP_ID, ESP_NOMBRE) VALUES (5,'DERMATOGOLÍA');
INSERT INTO ESPECIALIDAD VALUES (6,'LABORATORIO');

-- TIPO RESERVA

INSERT INTO TIPO_RESERVA VALUES (1,'ON-LINE');
INSERT INTO TIPO_RESERVA VALUES (2,'PRESENCIAL');
INSERT INTO TIPO_RESERVA VALUES (3,'TELÉFONO');

-- CAJA

INSERT INTO CAJA VALUES(1,'Caja 1');
INSERT INTO CAJA VALUES(2,'Caja 2');

-- TIPO USUARIO

INSERT INTO TIPO_USUARIO VALUES(1,'Developer');
INSERT INTO TIPO_USUARIO VALUES(2,'Admin');
INSERT INTO TIPO_USUARIO VALUES(3,'Médico');
INSERT INTO TIPO_USUARIO VALUES(4,'Secretaria');
INSERT INTO TIPO_USUARIO VALUES(5,'Cajero');


