-- Generado por Oracle SQL Developer Data Modeler 4.1.0.881
--   en:        2017-04-03 11:30:02 ART
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE AGENDA CASCADE CONSTRAINTS ;

DROP TABLE ATENCION CASCADE CONSTRAINTS ;

DROP TABLE CAJA CASCADE CONSTRAINTS ;

DROP TABLE CAJERO CASCADE CONSTRAINTS ;

DROP TABLE CAL_BASE CASCADE CONSTRAINTS ;

DROP TABLE CITA CASCADE CONSTRAINTS ;

DROP TABLE CTO_MEDICO CASCADE CONSTRAINTS ;

DROP TABLE DISPONIBLIDAD CASCADE CONSTRAINTS ;

DROP TABLE ERRORES CASCADE CONSTRAINTS ;

DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS ;

DROP TABLE ESTADO_AGENDA CASCADE CONSTRAINTS ;

DROP TABLE ESTADO_CITA CASCADE CONSTRAINTS ;

DROP TABLE FORMA_PAGO CASCADE CONSTRAINTS ;

DROP TABLE INFORME CASCADE CONSTRAINTS ;

DROP TABLE LOG_SESIONES CASCADE CONSTRAINTS ;

DROP TABLE MEDICO CASCADE CONSTRAINTS ;

DROP TABLE PACIENTE CASCADE CONSTRAINTS ;

DROP TABLE PREVISION CASCADE CONSTRAINTS ;

DROP TABLE REGISTRO_PAGO_COMISION CASCADE CONSTRAINTS ;

DROP TABLE SECRETARIA CASCADE CONSTRAINTS ;

DROP TABLE TIPO_PAGO CASCADE CONSTRAINTS ;

CREATE TABLE AGENDA
  (
    ID               INTEGER NOT NULL ,
    FECHA            DATE NOT NULL ,
    DISPONIBLIDAD_ID INTEGER NOT NULL ,
    ESTADO_AGENDA_ID INTEGER NOT NULL
  ) ;
ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE ATENCION
  (
    ID            INTEGER NOT NULL ,
    FECHA         TIMESTAMP NOT NULL ,
    VALOR         INTEGER NOT NULL ,
    ESTADO        SMALLINT NOT NULL ,
    CITA_ID       INTEGER NOT NULL ,
    FORMA_PAGO_ID INTEGER NOT NULL ,
    TIPO_PAGO_ID  INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX ATENCION__IDX ON ATENCION
  (
    CITA_ID ASC
  )
  ;
  ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE CAJA
  (
    ID          INTEGER NOT NULL ,
    NOMBRE      VARCHAR2 (255 CHAR) NOT NULL ,
    ESTADO      SMALLINT NOT NULL ,
    ATENCION_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CAJA ADD CONSTRAINT CAJA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE CAJERO
  (
    ID             INTEGER NOT NULL ,
    FECHA_CREACION TIMESTAMP NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO        VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO        VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES        VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL          VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA     VARCHAR2 (32 CHAR) NOT NULL ,
    CTO_MEDICO_ID  INTEGER NOT NULL
  ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE CAL_BASE
  (
    ID            INTEGER NOT NULL ,
    FECHA         DATE NOT NULL ,
    MOTIVO        VARCHAR2 (255 CHAR) ,
    CTO_MEDICO_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CAL_BASE ADD CONSTRAINT CAL_BASE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CITA
  (
    ID             INTEGER NOT NULL ,
    HORA_INICIO    DATE NOT NULL ,
    HORA_TERMINO   DATE NOT NULL ,
    AGENDA_ID      INTEGER NOT NULL ,
    PACIENTE_ID    INTEGER ,
    ESTADO_CITA_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CITA ADD CONSTRAINT CITA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE CTO_MEDICO
  (
    ID       INTEGER NOT NULL ,
    RUT      INTEGER NOT NULL ,
    DV       VARCHAR2 (1 CHAR) NOT NULL ,
    NOMBRE   VARCHAR2 (255 CHAR) NOT NULL ,
    TELEFONO INTEGER NOT NULL ,
    EMAIL    VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE CTO_MEDICO ADD CONSTRAINT CTO_MEDICO_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DISPONIBLIDAD
  (
    ID           INTEGER NOT NULL ,
    HORA_INICIO  DATE NOT NULL ,
    HORA_TERMINO DATE NOT NULL ,
    LUNES        SMALLINT NOT NULL ,
    MARTES       SMALLINT NOT NULL ,
    MIERCOLES    SMALLINT NOT NULL ,
    JUEVES       SMALLINT NOT NULL ,
    VIERNES      SMALLINT NOT NULL ,
    SABADO       SMALLINT NOT NULL ,
    DOMINGO      SMALLINT NOT NULL ,
    MEDICO_ID    INTEGER NOT NULL
  ) ;
ALTER TABLE DISPONIBLIDAD ADD CONSTRAINT DISPONIBLIDAD_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE ERRORES
  -- No Columns
  ;

CREATE TABLE ESPECIALIDAD
  (
    ID     INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (200 CHAR) NOT NULL
  ) ;
ALTER TABLE ESPECIALIDAD ADD CONSTRAINT ESPECIALIDAD_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE ESTADO_AGENDA
  (
    ID          INTEGER NOT NULL ,
    DESCRIPCION VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE ESTADO_AGENDA ADD CONSTRAINT ESTADO_AGENDA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE ESTADO_CITA
  (
    ID     INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE ESTADO_CITA ADD CONSTRAINT ESTADO_CITA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE FORMA_PAGO
  (
    ID     INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT FORMA_PAGO_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE INFORME
  (
    ID          INTEGER NOT NULL ,
    PORCENTAJE  NUMBER (5,2) NOT NULL ,
    COMISION    INTEGER NOT NULL ,
    ATENCION_ID INTEGER NOT NULL
  ) ;
ALTER TABLE INFORME ADD CONSTRAINT INFORME_PKv1 PRIMARY KEY ( ID ) ;

CREATE TABLE LOG_SESIONES
  -- No Columns
  ;

CREATE TABLE MEDICO
  (
    ID              INTEGER NOT NULL ,
    FECHA_CREACION  DATE NOT NULL ,
    RUT             INTEGER NOT NULL ,
    DV              VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO         VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO         VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES         VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL           VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA      VARCHAR2 (32 CHAR) NOT NULL ,
    ESPECIALIDAD_ID INTEGER NOT NULL ,
    CTO_MEDICO_ID   INTEGER NOT NULL
  ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE PACIENTE
  (
    ID             INTEGER NOT NULL ,
    FECHA_CREACION DATE NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1 CHAR) NOT NULL ,
    DIRECCION      VARCHAR2 (255 CHAR) NOT NULL ,
    TELEFONO       INTEGER NOT NULL ,
    EMAIL          VARCHAR2 (255 CHAR) NOT NULL ,
    PREVISION_ID   INTEGER NOT NULL ,
    ID11           INTEGER NOT NULL ,
    PASS           VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE PREVISION
  (
    ID     INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE PREVISION ADD CONSTRAINT PREVISION_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE REGISTRO_PAGO_COMISION
  (
    ID    INTEGER NOT NULL ,
    TOTAL INTEGER NOT NULL
  ) ;
ALTER TABLE REGISTRO_PAGO_COMISION ADD CONSTRAINT REGISTRO_PAGO_COMISION_PKv1 PRIMARY KEY ( ID ) ;

CREATE TABLE SECRETARIA
  (
    ID             INTEGER NOT NULL ,
    FECHA_CREACION TIMESTAMP NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO        VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO        VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES        VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL          VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA     VARCHAR2 (32 CHAR) NOT NULL ,
    CTO_MEDICO_ID  INTEGER NOT NULL
  ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PKv2 PRIMARY KEY ( ID ) ;

CREATE TABLE TIPO_PAGO
  (
    ID     INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE TIPO_PAGO ADD CONSTRAINT TIPO_PAGO_PKv2 PRIMARY KEY ( ID ) ;

ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_DISPONIBLIDAD_FKv1 FOREIGN KEY ( DISPONIBLIDAD_ID ) REFERENCES DISPONIBLIDAD ( ID ) ;

ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_ESTADO_AGENDA_FKv1 FOREIGN KEY ( ESTADO_AGENDA_ID ) REFERENCES ESTADO_AGENDA ( ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_CITA_FK FOREIGN KEY ( CITA_ID ) REFERENCES CITA ( ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_FORMA_PAGO_FKv1 FOREIGN KEY ( FORMA_PAGO_ID ) REFERENCES FORMA_PAGO ( ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_TIPO_PAGO_FKv1 FOREIGN KEY ( TIPO_PAGO_ID ) REFERENCES TIPO_PAGO ( ID ) ;

ALTER TABLE CAJA ADD CONSTRAINT CAJA_ATENCION_FKv1 FOREIGN KEY ( ATENCION_ID ) REFERENCES ATENCION ( ID ) ;

ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_CTO_MEDICO_FK FOREIGN KEY ( CTO_MEDICO_ID ) REFERENCES CTO_MEDICO ( ID ) ;

ALTER TABLE CAL_BASE ADD CONSTRAINT CAL_BASE_CTO_MEDICO_FK FOREIGN KEY ( CTO_MEDICO_ID ) REFERENCES CTO_MEDICO ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_AGENDA_FK FOREIGN KEY ( AGENDA_ID ) REFERENCES AGENDA ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_ESTADO_CITA_FK FOREIGN KEY ( ESTADO_CITA_ID ) REFERENCES ESTADO_CITA ( ID ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID ) REFERENCES PACIENTE ( ID ) ;

ALTER TABLE DISPONIBLIDAD ADD CONSTRAINT DISPONIBLIDAD_MEDICO_FKv1 FOREIGN KEY ( MEDICO_ID ) REFERENCES MEDICO ( ID ) ;

ALTER TABLE INFORME ADD CONSTRAINT INFORME_ATENCION_FK FOREIGN KEY ( ATENCION_ID ) REFERENCES ATENCION ( ID ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_CTO_MEDICO_FK FOREIGN KEY ( CTO_MEDICO_ID ) REFERENCES CTO_MEDICO ( ID ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD_FKv1 FOREIGN KEY ( ESPECIALIDAD_ID ) REFERENCES ESPECIALIDAD ( ID ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PREVISION_FK FOREIGN KEY ( PREVISION_ID ) REFERENCES PREVISION ( ID ) ;

ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_CTO_MEDICO_FK FOREIGN KEY ( CTO_MEDICO_ID ) REFERENCES CTO_MEDICO ( ID ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             1
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
