//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ATENCION
{
    public ATENCION()
    {
        this.RECAUDACION = new HashSet<RECAUDACION>();
        this.RESERVA = new HashSet<RESERVA>();
    }

    public decimal ATE_ID { get; set; }
    public decimal TIPO_PAGO_TPA_ID { get; set; }
    public decimal FORMA_PAGO_FPA_ID { get; set; }
    public decimal CAJA_CAJ_ID { get; set; }

    public virtual CAJA CAJA { get; set; }
    public virtual FORMA_PAGO FORMA_PAGO { get; set; }
    public virtual TIPO_PAGO TIPO_PAGO { get; set; }
    public virtual ICollection<RECAUDACION> RECAUDACION { get; set; }
    public virtual ICollection<RESERVA> RESERVA { get; set; }
}

public partial class CAJA
{
    public CAJA()
    {
        this.ATENCION = new HashSet<ATENCION>();
        this.CAJERO = new HashSet<CAJERO>();
    }

    public decimal CAJ_ID { get; set; }
    public string CAJ_NOMBRE { get; set; }

    public virtual ICollection<ATENCION> ATENCION { get; set; }
    public virtual ICollection<CAJERO> CAJERO { get; set; }
}

public partial class CAJERO
{
    public decimal PER_ID { get; set; }
    public decimal CJR_ID { get; set; }
    public decimal CAJA_CAJ_ID { get; set; }

    public virtual CAJA CAJA { get; set; }
    public virtual PERSONAL PERSONAL { get; set; }
}

public partial class CALENDARIO
{
    public decimal CAL_ID { get; set; }
    public decimal CAL_MES { get; set; }
    public decimal HORARIO_HOR_ID { get; set; }

    public virtual HORARIO HORARIO { get; set; }
}

public partial class CENTRO_MEDICO
{
    public CENTRO_MEDICO()
    {
        this.MEDICO = new HashSet<MEDICO>();
    }

    public decimal CME_ID { get; set; }
    public string CME_NOMBRE { get; set; }
    public string CME_DIRECCION { get; set; }
    public string CME_EMAIL { get; set; }
    public decimal CME_TELEFONO { get; set; }
    public System.DateTime CME_HORA_APERT { get; set; }
    public System.DateTime CME_HORA_CIERRE { get; set; }

    public virtual ICollection<MEDICO> MEDICO { get; set; }
}

public partial class ERRORES
{
    public decimal ID { get; set; }
    public System.DateTime FECHA { get; set; }
    public string TABLA { get; set; }
    public string CODIGO_ERROR { get; set; }
    public string DETALLE { get; set; }
}

public partial class ESPECIALIDAD
{
    public ESPECIALIDAD()
    {
        this.MEDICO = new HashSet<MEDICO>();
    }

    public decimal ESP_ID { get; set; }
    public string ESP_NOMBRE { get; set; }

    public virtual ICollection<MEDICO> MEDICO { get; set; }
}

public partial class FORMA_PAGO
{
    public FORMA_PAGO()
    {
        this.ATENCION = new HashSet<ATENCION>();
    }

    public decimal FPA_ID { get; set; }
    public string FPA_NOMBRE { get; set; }

    public virtual ICollection<ATENCION> ATENCION { get; set; }
}

public partial class HORARIO
{
    public HORARIO()
    {
        this.CALENDARIO = new HashSet<CALENDARIO>();
    }

    public decimal HOR_ID { get; set; }
    public decimal HOR_LUNES { get; set; }
    public decimal HOR_MARTES { get; set; }
    public decimal HOR_MIERCOLES { get; set; }
    public decimal HOR_JUEVES { get; set; }
    public decimal HOR_VIERNES { get; set; }
    public decimal HOR_SABADO { get; set; }
    public decimal HOR_DOMINGO { get; set; }
    public System.DateTime HOR_INICIO { get; set; }
    public System.DateTime HOR_TERMINO { get; set; }
    public decimal MEDICO_MED_ID { get; set; }

    public virtual ICollection<CALENDARIO> CALENDARIO { get; set; }
    public virtual MEDICO MEDICO { get; set; }
}

public partial class LOG_RESERVA
{
    public decimal ID { get; set; }
    public string FECHA { get; set; }
    public string ESTADO { get; set; }
    public decimal ID_USUARIO { get; set; }
    public decimal ID_RESERVA { get; set; }
}

public partial class MEDICO
{
    public MEDICO()
    {
        this.HORARIO = new HashSet<HORARIO>();
        this.RESERVA = new HashSet<RESERVA>();
    }

    public decimal MED_ID { get; set; }
    public string MED_NOMBRES { get; set; }
    public string MED_PATERNO { get; set; }
    public string MED_MATERNO { get; set; }
    public decimal CENTRO_MEDICO_CME_ID { get; set; }
    public decimal ESPECIALIDAD_ESP_ID { get; set; }
    public decimal MED_MIN_AT { get; set; }
    public decimal MED_VALOR_AT { get; set; }
    public decimal USUARIO_USU_ID { get; set; }

    public virtual CENTRO_MEDICO CENTRO_MEDICO { get; set; }
    public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
    public virtual ICollection<HORARIO> HORARIO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
    public virtual ICollection<RESERVA> RESERVA { get; set; }
}

public partial class PACIENTE
{
    public PACIENTE()
    {
        this.RESERVA = new HashSet<RESERVA>();
    }

    public decimal PAC_ID { get; set; }
    public decimal PAC_RUT { get; set; }
    public string PAC_DV { get; set; }
    public string PAC_NOMBRES { get; set; }
    public string PAC_PATERNO { get; set; }
    public string PAC_MATERNO { get; set; }
    public System.DateTime PAC_FNAC { get; set; }
    public string PAC_DIRECCION { get; set; }
    public Nullable<decimal> PAC_CELULAR { get; set; }
    public Nullable<decimal> PAC_TELEFONO { get; set; }
    public decimal PREVISION_PRE_ID { get; set; }
    public decimal USUARIO_USU_ID { get; set; }

    public virtual PREVISION PREVISION { get; set; }
    public virtual USUARIO USUARIO { get; set; }
    public virtual ICollection<RESERVA> RESERVA { get; set; }
}

public partial class PERSONAL
{
    public decimal PER_ID { get; set; }
    public decimal RUT { get; set; }
    public string DV { get; set; }
    public string NOMBRES { get; set; }
    public string PATERNO { get; set; }
    public string MATERNO { get; set; }
    public System.DateTime FNAC { get; set; }
    public string DIRECCION { get; set; }
    public Nullable<decimal> CELULAR { get; set; }
    public Nullable<decimal> TELEFONO { get; set; }
    public decimal ESTADO { get; set; }
    public System.DateTime FECHA_REGISTRO { get; set; }
    public decimal USUARIO_USU_ID { get; set; }

    public virtual CAJERO CAJERO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
    public virtual SECRETARIA SECRETARIA { get; set; }
}

public partial class PREVISION
{
    public PREVISION()
    {
        this.PACIENTE = new HashSet<PACIENTE>();
    }

    public decimal PRE_ID { get; set; }
    public string PRE_NOMBRE { get; set; }

    public virtual ICollection<PACIENTE> PACIENTE { get; set; }
}

public partial class RECAUDACION
{
    public decimal REC_ID { get; set; }
    public decimal ATENCION_ATE_ID { get; set; }
    public decimal REC_PORCENTAJE { get; set; }
    public decimal REC_TOTAL { get; set; }

    public virtual ATENCION ATENCION { get; set; }
}

public partial class RESERVA
{
    public decimal RES_ID { get; set; }
    public System.DateTime RES_FECHA { get; set; }
    public System.DateTime RES_HORA_INICIO { get; set; }
    public System.DateTime RES_HORA_TERM { get; set; }
    public decimal MEDICO_MED_ID { get; set; }
    public decimal PACIENTE_PAC_ID { get; set; }
    public decimal TIPO_RESERVA_TRE_ID { get; set; }
    public decimal RES_ESTADO { get; set; }
    public decimal ATENCION_ATE_ID { get; set; }

    public virtual ATENCION ATENCION { get; set; }
    public virtual MEDICO MEDICO { get; set; }
    public virtual PACIENTE PACIENTE { get; set; }
    public virtual TIPO_RESERVA TIPO_RESERVA { get; set; }
}

public partial class SECRETARIA
{
    public decimal PER_ID { get; set; }
    public decimal SEC_ID { get; set; }

    public virtual PERSONAL PERSONAL { get; set; }
}

public partial class TIPO_PAGO
{
    public TIPO_PAGO()
    {
        this.ATENCION = new HashSet<ATENCION>();
    }

    public decimal TPA_ID { get; set; }
    public string TPA_NOMBRE { get; set; }

    public virtual ICollection<ATENCION> ATENCION { get; set; }
}

public partial class TIPO_RESERVA
{
    public TIPO_RESERVA()
    {
        this.RESERVA = new HashSet<RESERVA>();
    }

    public decimal TRE_ID { get; set; }
    public string TRE_NOMBRE { get; set; }

    public virtual ICollection<RESERVA> RESERVA { get; set; }
}

public partial class TIPO_USUARIO
{
    public TIPO_USUARIO()
    {
        this.USUARIO = new HashSet<USUARIO>();
    }

    public decimal TU_ID { get; set; }
    public string TU_NOMBRE { get; set; }

    public virtual ICollection<USUARIO> USUARIO { get; set; }
}

public partial class USUARIO
{
    public USUARIO()
    {
        this.MEDICO = new HashSet<MEDICO>();
        this.PACIENTE = new HashSet<PACIENTE>();
        this.PERSONAL = new HashSet<PERSONAL>();
    }

    public decimal USU_ID { get; set; }
    public string USU_USERNAME { get; set; }
    public string USU_PASS { get; set; }
    public string USU_ULTIMOPASS { get; set; }
    public System.DateTime USU_FREGISTRO { get; set; }
    public decimal USU_ESTADO { get; set; }
    public Nullable<decimal> TIPO_USUARIO_TU_ID { get; set; }
    public string USU_EMAIL { get; set; }

    public virtual ICollection<MEDICO> MEDICO { get; set; }
    public virtual ICollection<PACIENTE> PACIENTE { get; set; }
    public virtual ICollection<PERSONAL> PERSONAL { get; set; }
    public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
}
