-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2017-04-06 18:40:13 CLST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE AGENDA
  (
    ID_AG                 INTEGER NOT NULL ,
    FECHA                 DATE NOT NULL ,
    DISPONIBLIDAD_ID_DISP INTEGER NOT NULL ,
    ESTADO_AGENDA_ID_EA   INTEGER NOT NULL
  ) ;
ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_PK PRIMARY KEY ( ID_AG ) ;


CREATE TABLE ATENCION
  (
    ID_AT               INTEGER NOT NULL ,
    FECHA               TIMESTAMP NOT NULL ,
    VALOR               INTEGER NOT NULL ,
    ESTADO              SMALLINT NOT NULL ,
    CITA_ID_CT          INTEGER NOT NULL ,
    FORMA_PAGO_ID_F_PGO INTEGER NOT NULL ,
    TIPO_PAGO_ID_T_PGO  INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX ATENCION__IDX ON ATENCION
  (
    CITA_ID_CT ASC
  )
  ;
ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_PK PRIMARY KEY ( ID_AT ) ;


CREATE TABLE CAJA
  (
    ID_CJ          INTEGER NOT NULL ,
    NOMBRE         VARCHAR2 (255 CHAR) NOT NULL ,
    ESTADO         SMALLINT NOT NULL ,
    ATENCION_ID_AT INTEGER NOT NULL
  ) ;
ALTER TABLE CAJA ADD CONSTRAINT CAJA_PK PRIMARY KEY ( ID_CJ ) ;


CREATE TABLE CAJERO
  (
    ID_CAJ              INTEGER NOT NULL ,
    FECHA_CREACION      TIMESTAMP NOT NULL ,
    RUT                 INTEGER NOT NULL ,
    DV                  VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES             VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL               VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA          VARCHAR2 (32 CHAR) NOT NULL ,
    CENTRO_MEDICO_ID_CM INTEGER NOT NULL
  ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_PK PRIMARY KEY ( ID_CAJ ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_RUT_UN UNIQUE ( RUT ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_EMAIL_UN UNIQUE ( EMAIL ) ;


CREATE TABLE CB
  (
    ID_CB               INTEGER NOT NULL ,
    FECHA               DATE NOT NULL ,
    MOTIVO              VARCHAR2 (255 CHAR) ,
    CENTRO_MEDICO_ID_CM INTEGER NOT NULL
  ) ;
ALTER TABLE CB ADD CONSTRAINT CB_PK PRIMARY KEY ( ID_CB ) ;


CREATE TABLE CENTRO_MEDICO
  (
    ID_CM    INTEGER NOT NULL ,
    RUT      INTEGER NOT NULL ,
    DV       VARCHAR2 (1 CHAR) NOT NULL ,
    NOMBRE   VARCHAR2 (255 CHAR) NOT NULL ,
    TELEFONO INTEGER NOT NULL ,
    EMAIL    VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE CENTRO_MEDICO ADD CONSTRAINT CENTRO_MEDICO_PK PRIMARY KEY ( ID_CM ) ;
ALTER TABLE CENTRO_MEDICO ADD CONSTRAINT CENTRO_MEDICO_RUT_UN UNIQUE ( RUT ) ;
ALTER TABLE CENTRO_MEDICO ADD CONSTRAINT CENTRO_MEDICO_EMAIL_UN UNIQUE ( EMAIL ) ;


CREATE TABLE CITA
  (
    ID_CT                 INTEGER NOT NULL ,
    HORA_INICIO           DATE NOT NULL ,
    HORA_TERMINO          DATE NOT NULL ,
    AGENDA_ID_AG          INTEGER NOT NULL ,
    PACIENTE_ID_PACIENTE  INTEGER ,
    ESTADO_CITA_ID_EST_CT INTEGER NOT NULL
  ) ;
ALTER TABLE CITA ADD CONSTRAINT CITA_PK PRIMARY KEY ( ID_CT ) ;


CREATE TABLE DISPONIBLIDAD
  (
    ID_DISP          INTEGER NOT NULL ,
    HORA_INICIO      DATE NOT NULL ,
    HORA_TERMINO     DATE NOT NULL ,
    LUNES            SMALLINT NOT NULL ,
    MARTES           SMALLINT NOT NULL ,
    MIERCOLES        SMALLINT NOT NULL ,
    JUEVES           SMALLINT NOT NULL ,
    VIERNES          SMALLINT NOT NULL ,
    SABADO           SMALLINT NOT NULL ,
    DOMINGO          SMALLINT NOT NULL ,
    MEDICO_ID_MD     INTEGER NOT NULL ,
    EST_DISP_ID_DISP INTEGER NOT NULL ,
    ID_DISP11        INTEGER NOT NULL
  ) ;
ALTER TABLE DISPONIBLIDAD ADD CONSTRAINT DISPONIBLIDAD_PK PRIMARY KEY ( ID_DISP ) ;


CREATE TABLE ERRORES
  (
    ID_ERROR    INTEGER NOT NULL ,
    COD         INTEGER NOT NULL ,
    DESCRIPCION VARCHAR2 (200) NOT NULL ,
    FECHA       DATE NOT NULL
  ) ;
ALTER TABLE ERRORES ADD CONSTRAINT ERRORES_PK PRIMARY KEY ( ID_ERROR ) ;


CREATE TABLE ESPECIALIDAD
  (
    ID_ESP INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (200 CHAR) NOT NULL
  ) ;
ALTER TABLE ESPECIALIDAD ADD CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY ( ID_ESP ) ;


CREATE TABLE ESTADO_AGENDA
  (
    ID_EA       INTEGER NOT NULL ,
    DESCRIPCION VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE ESTADO_AGENDA ADD CONSTRAINT ESTADO_AGENDA_PK PRIMARY KEY ( ID_EA ) ;


CREATE TABLE ESTADO_CITA
  (
    ID_EST_CT INTEGER NOT NULL ,
    NOMBRE    VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE ESTADO_CITA ADD CONSTRAINT ESTADO_CITA_PK PRIMARY KEY ( ID_EST_CT ) ;


CREATE TABLE EST_DISP
  (
    ID_DISP INTEGER NOT NULL ,
    ESTADO  VARCHAR2 (20 CHAR) NOT NULL
  ) ;
ALTER TABLE EST_DISP ADD CONSTRAINT EST_DISP_PK PRIMARY KEY ( ID_DISP ) ;


CREATE TABLE FORMA_PAGO
  (
    ID_F_PGO INTEGER NOT NULL ,
    NOMBRE   VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT FORMA_PAGO_PK PRIMARY KEY ( ID_F_PGO ) ;


CREATE TABLE INFORME
  (
    ID_INF         INTEGER NOT NULL ,
    PORCENTAJE     NUMBER (5,2) NOT NULL ,
    COMISION       INTEGER NOT NULL ,
    ATENCION_ID_AT INTEGER NOT NULL
  ) ;
ALTER TABLE INFORME ADD CONSTRAINT INFORME_PK PRIMARY KEY ( ID_INF ) ;


CREATE TABLE LOG_CITAS
  (
    ID             INTEGER NOT NULL ,
    ID_PACIENTE    INTEGER NOT NULL ,
    FECHA_CREACION DATE NOT NULL ,
    ESTADO_OLD     VARCHAR2 (100) NOT NULL ,
    ESTADO_NEW     VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE LOG_CITAS ADD CONSTRAINT LOG_CITAS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE LOG_SESIONES
  (
    ID         INTEGER NOT NULL ,
    ID_USUARIO INTEGER NOT NULL ,
    FECHA      DATE NOT NULL
  ) ;
ALTER TABLE LOG_SESIONES ADD CONSTRAINT LOG_SESIONES_PK PRIMARY KEY ( ID ) ;


CREATE TABLE MEDICO
  (
    ID_MD               INTEGER NOT NULL ,
    FECHA_CREACION      DATE NOT NULL ,
    RUT                 INTEGER NOT NULL ,
    DV                  VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES             VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL               VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA          VARCHAR2 (32 CHAR) NOT NULL ,
    ESPECIALIDAD_ID_ESP INTEGER NOT NULL ,
    CENTRO_MEDICO_ID_CM INTEGER NOT NULL
  ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_PK PRIMARY KEY ( ID_MD ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_RUT_UN UNIQUE ( RUT ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_EMAIL_UN UNIQUE ( EMAIL ) ;


CREATE TABLE PACIENTE
  (
    ID_PACIENTE       INTEGER NOT NULL ,
    FECHA_CREACION    DATE NOT NULL ,
    RUT               INTEGER NOT NULL ,
    DV                VARCHAR2 (1 CHAR) NOT NULL ,
    DIRECCION         VARCHAR2 (255 CHAR) NOT NULL ,
    TELEFONO          INTEGER NOT NULL ,
    EMAIL             VARCHAR2 (255 CHAR) NOT NULL ,
    PREVISION_ID_PREV INTEGER NOT NULL ,
    PASS              VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( ID_PACIENTE ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_RUT_UN UNIQUE ( RUT ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_EMAIL_UN UNIQUE ( EMAIL ) ;


CREATE TABLE PREVISION
  (
    ID_PREV INTEGER NOT NULL ,
    NOMBRE  VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE PREVISION ADD CONSTRAINT PREVISION_PK PRIMARY KEY ( ID_PREV ) ;


CREATE TABLE REG_PAGO_COM
  (
    ID_PG_C      INTEGER NOT NULL ,
    TOTAL        INTEGER NOT NULL ,
    FECHA        DATE ,
    MEDICO_ID_MD INTEGER NOT NULL
  ) ;
ALTER TABLE REG_PAGO_COM ADD CONSTRAINT REG_PAG_COM_PK PRIMARY KEY ( ID_PG_C ) ;


CREATE TABLE REG_USERS
  (
    ID      INTEGER NOT NULL ,
    RUT     INTEGER NOT NULL ,
    N_TABLA VARCHAR2 (25) NOT NULL ,
    ID_USER INTEGER NOT NULL
  ) ;
ALTER TABLE REG_USERS ADD CONSTRAINT REG_USERS_PK PRIMARY KEY ( ID ) ;


CREATE TABLE SECRETARIA
  (
    ID_SEC              INTEGER NOT NULL ,
    FECHA_CREACION      TIMESTAMP NOT NULL ,
    RUT                 INTEGER NOT NULL ,
    DV                  VARCHAR2 (1 CHAR) NOT NULL ,
    PATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    MATERNO             VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRES             VARCHAR2 (100 CHAR) NOT NULL ,
    EMAIL               VARCHAR2 (255 CHAR) NOT NULL ,
    CONTRASENA          VARCHAR2 (32 CHAR) NOT NULL ,
    CENTRO_MEDICO_ID_CM INTEGER NOT NULL
  ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PK PRIMARY KEY ( ID_SEC ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_RUT_UN UNIQUE ( RUT ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_EMAIL_UN UNIQUE ( EMAIL ) ;


CREATE TABLE TIPO_PAGO
  (
    ID_T_PGO INTEGER NOT NULL ,
    NOMBRE   VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE TIPO_PAGO ADD CONSTRAINT TIPO_PAGO_PK PRIMARY KEY ( ID_T_PGO ) ;


ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_DISPONIBLIDAD_FK FOREIGN KEY ( DISPONIBLIDAD_ID_DISP ) REFERENCES DISPONIBLIDAD ( ID_DISP ) ;

ALTER TABLE AGENDA ADD CONSTRAINT AGENDA_ESTADO_AGENDA_FK FOREIGN KEY ( ESTADO_AGENDA_ID_EA ) REFERENCES ESTADO_AGENDA ( ID_EA ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_CITA_FK FOREIGN KEY ( CITA_ID_CT ) REFERENCES CITA ( ID_CT ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_FORMA_PAGO_FK FOREIGN KEY ( FORMA_PAGO_ID_F_PGO ) REFERENCES FORMA_PAGO ( ID_F_PGO ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_TIPO_PAGO_FK FOREIGN KEY ( TIPO_PAGO_ID_T_PGO ) REFERENCES TIPO_PAGO ( ID_T_PGO ) ;

ALTER TABLE CAJA ADD CONSTRAINT CAJA_ATENCION_FK FOREIGN KEY ( ATENCION_ID_AT ) REFERENCES ATENCION ( ID_AT ) ;

ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_CENTRO_MEDICO_FK FOREIGN KEY ( CENTRO_MEDICO_ID_CM ) REFERENCES CENTRO_MEDICO ( ID_CM ) ;

ALTER TABLE CB ADD CONSTRAINT CB_CENTRO_MEDICO_FK FOREIGN KEY ( CENTRO_MEDICO_ID_CM ) REFERENCES CENTRO_MEDICO ( ID_CM ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_AGENDA_FK FOREIGN KEY ( AGENDA_ID_AG ) REFERENCES AGENDA ( ID_AG ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_ESTADO_CITA_FK FOREIGN KEY ( ESTADO_CITA_ID_EST_CT ) REFERENCES ESTADO_CITA ( ID_EST_CT ) ;

ALTER TABLE CITA ADD CONSTRAINT CITA_PACIENTE_FK FOREIGN KEY ( PACIENTE_ID_PACIENTE ) REFERENCES PACIENTE ( ID_PACIENTE ) ;

ALTER TABLE DISPONIBLIDAD ADD CONSTRAINT DISPONIBLIDAD_EST_DISP_FK FOREIGN KEY ( EST_DISP_ID_DISP ) REFERENCES EST_DISP ( ID_DISP ) ;

ALTER TABLE DISPONIBLIDAD ADD CONSTRAINT DISPONIBLIDAD_MEDICO_FK FOREIGN KEY ( MEDICO_ID_MD ) REFERENCES MEDICO ( ID_MD ) ;

ALTER TABLE INFORME ADD CONSTRAINT INFORME_ATENCION_FK FOREIGN KEY ( ATENCION_ID_AT ) REFERENCES ATENCION ( ID_AT ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_CENTRO_MEDICO_FK FOREIGN KEY ( CENTRO_MEDICO_ID_CM ) REFERENCES CENTRO_MEDICO ( ID_CM ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY ( ESPECIALIDAD_ID_ESP ) REFERENCES ESPECIALIDAD ( ID_ESP ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PREVISION_FK FOREIGN KEY ( PREVISION_ID_PREV ) REFERENCES PREVISION ( ID_PREV ) ;

ALTER TABLE REG_PAGO_COM ADD CONSTRAINT REG_PAG_COM_MEDICO_FK FOREIGN KEY ( MEDICO_ID_MD ) REFERENCES MEDICO ( ID_MD ) ;

ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_CENTRO_MEDICO_FK FOREIGN KEY ( CENTRO_MEDICO_ID_CM ) REFERENCES CENTRO_MEDICO ( ID_CM ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            24
-- CREATE INDEX                             1
-- ALTER TABLE                             53
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
