//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA_INICIO { get; set; }
        public System.DateTime HORA_TERMINO { get; set; }
        public int MEDICO_ID { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
    }
}
