//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO_BASE
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MOTIVO { get; set; }
        public int CENTRO_MEDICO_ID { get; set; }
    
        public virtual CENTRO_MEDICO CENTRO_MEDICO { get; set; }
    }
}
