//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CentroMedicoEntities : DbContext
    {
        public CentroMedicoEntities()
            : base("name=CentroMedicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENDA> AGENDA { get; set; }
        public DbSet<CALENDARIO_BASE> CALENDARIO_BASE { get; set; }
        public DbSet<CENTRO_MEDICO> CENTRO_MEDICO { get; set; }
        public DbSet<DISPONIBILIDAD> DISPONIBILIDAD { get; set; }
        public DbSet<ESPECIALIDAD> ESPECIALIDAD { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<SECRETARIA> SECRETARIA { get; set; }
    
        public virtual int ESPECIALIDAD_DEL(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESPECIALIDAD_DEL", p_IDParameter);
        }
    
        public virtual int ESPECIALIDAD_INS(Nullable<int> p_ID, string p_NOMBRE)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESPECIALIDAD_INS", p_IDParameter, p_NOMBREParameter);
        }
    }
}
