--------------------------------------------------------
-- Archivo creado  - domingo-abril-16-2017   
--------------------------------------------------------
DROP TABLE "CMDBA"."AGENDA" cascade constraints;
DROP TABLE "CMDBA"."CALENDARIO_BASE" cascade constraints;
DROP TABLE "CMDBA"."CENTRO_MEDICO" cascade constraints;
DROP TABLE "CMDBA"."DISPONIBILIDAD" cascade constraints;
DROP TABLE "CMDBA"."ESPECIALIDAD" cascade constraints;
DROP TABLE "CMDBA"."MEDICO" cascade constraints;
DROP TABLE "CMDBA"."SECRETARIA" cascade constraints;
DROP SEQUENCE "CMDBA"."SEQ_AGENDA";
DROP SEQUENCE "CMDBA"."SEQ_CBASE";
DROP SEQUENCE "CMDBA"."SEQ_CMEDICO";
DROP SEQUENCE "CMDBA"."SEQ_DISPONIBILIDAD";
DROP SEQUENCE "CMDBA"."SEQ_ESPECIALIDAD";
DROP SEQUENCE "CMDBA"."SEQ_MEDICO";
DROP SEQUENCE "CMDBA"."SEQ_SECRETARIA";
--------------------------------------------------------
--  DDL for Sequence SEQ_AGENDA
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_AGENDA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CBASE
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_CBASE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CMEDICO
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_CMEDICO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DISPONIBILIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_DISPONIBILIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ESPECIALIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_ESPECIALIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEDICO
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_MEDICO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SECRETARIA
--------------------------------------------------------

   CREATE SEQUENCE  "CMDBA"."SEQ_SECRETARIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AGENDA
--------------------------------------------------------

  CREATE TABLE "CMDBA"."AGENDA" 
   (	"ID" NUMBER(7,0), 
	"FECHA" DATE, 
	"HORA_INICIO" DATE, 
	"HORA_TERMINO" DATE, 
	"MEDICO_ID" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CALENDARIO_BASE
--------------------------------------------------------

  CREATE TABLE "CMDBA"."CALENDARIO_BASE" 
   (	"ID" NUMBER(7,0), 
	"FECHA" DATE, 
	"MOTIVO" VARCHAR2(255 CHAR), 
	"CENTRO_MEDICO_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CENTRO_MEDICO
--------------------------------------------------------

  CREATE TABLE "CMDBA"."CENTRO_MEDICO" 
   (	"ID" NUMBER(7,0), 
	"RUT" NUMBER(9,0), 
	"DV" VARCHAR2(1 CHAR), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"DIRECCION" VARCHAR2(255 CHAR), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISPONIBILIDAD
--------------------------------------------------------

  CREATE TABLE "CMDBA"."DISPONIBILIDAD" 
   (	"ID" NUMBER(7,0), 
	"HORA_INICIO" DATE, 
	"HORA_TERMINO" DATE, 
	"LUNES" NUMBER(*,0), 
	"MARTES" NUMBER(*,0), 
	"MIERCOLES" NUMBER(*,0), 
	"JUEVES" NUMBER(*,0), 
	"VIERNES" NUMBER(*,0), 
	"SABADO" NUMBER(*,0), 
	"DOMINGO" NUMBER(*,0), 
	"MEDICO_ID" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESPECIALIDAD
--------------------------------------------------------

  CREATE TABLE "CMDBA"."ESPECIALIDAD" 
   (	"ID" NUMBER(7,0), 
	"NOMBRE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICO
--------------------------------------------------------

  CREATE TABLE "CMDBA"."MEDICO" 
   (	"ID" NUMBER(7,0), 
	"FECHA_CREACION" DATE, 
	"RUT" NUMBER(8,0), 
	"DV" VARCHAR2(1 CHAR), 
	"PATERNO" VARCHAR2(100 CHAR), 
	"MATERNO" VARCHAR2(100 CHAR), 
	"NOMBRES" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(25 CHAR), 
	"CLAVE" VARCHAR2(64 CHAR), 
	"MINUTOS_ATENCION" NUMBER(3,0), 
	"CENTRO_MEDICO_ID" NUMBER(7,0), 
	"ESPECIALIDAD_ID" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SECRETARIA
--------------------------------------------------------

  CREATE TABLE "CMDBA"."SECRETARIA" 
   (	"ID" NUMBER(7,0), 
	"FECHA_CREACION" DATE, 
	"RUT" NUMBER(8,0), 
	"DV" VARCHAR2(1 CHAR), 
	"PATERNO" VARCHAR2(100 CHAR), 
	"MATERNO" VARCHAR2(100 CHAR), 
	"NOMBRES" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(25 CHAR), 
	"CLAVE" VARCHAR2(64 CHAR), 
	"CENTRO_MEDICO_ID" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CMDBA.AGENDA
SET DEFINE OFF;
REM INSERTING into CMDBA.CALENDARIO_BASE
SET DEFINE OFF;
REM INSERTING into CMDBA.CENTRO_MEDICO
SET DEFINE OFF;
REM INSERTING into CMDBA.DISPONIBILIDAD
SET DEFINE OFF;
REM INSERTING into CMDBA.ESPECIALIDAD
SET DEFINE OFF;
Insert into CMDBA.ESPECIALIDAD (ID,NOMBRE) values ('1','MEDICINA GENERAL');
REM INSERTING into CMDBA.MEDICO
SET DEFINE OFF;
REM INSERTING into CMDBA.SECRETARIA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SECRETARIA_RUT_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."SECRETARIA_RUT_UNV1" ON "CMDBA"."SECRETARIA" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CENTRO_MEDICO_RUT_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."CENTRO_MEDICO_RUT_UNV1" ON "CMDBA"."CENTRO_MEDICO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SECRETARIA_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."SECRETARIA_PKV1" ON "CMDBA"."SECRETARIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CALENDARIO_BASE_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."CALENDARIO_BASE_PKV1" ON "CMDBA"."CALENDARIO_BASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICO_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."MEDICO_PKV1" ON "CMDBA"."MEDICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESPECIALIDAD_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."ESPECIALIDAD_PKV1" ON "CMDBA"."ESPECIALIDAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICO_EMAIL_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."MEDICO_EMAIL_UNV1" ON "CMDBA"."MEDICO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CENTRO_MEDICO_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."CENTRO_MEDICO_PKV1" ON "CMDBA"."CENTRO_MEDICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISPONIBILIDAD_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."DISPONIBILIDAD_PKV1" ON "CMDBA"."DISPONIBILIDAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SECRETARIA_EMAIL_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."SECRETARIA_EMAIL_UNV1" ON "CMDBA"."SECRETARIA" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICO_RUT_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."MEDICO_RUT_UNV1" ON "CMDBA"."MEDICO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CENTRO_MEDICO_EMAIL_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."CENTRO_MEDICO_EMAIL_UNV1" ON "CMDBA"."CENTRO_MEDICO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AGENDA_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CMDBA"."AGENDA_PKV1" ON "CMDBA"."AGENDA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SECRETARIA
--------------------------------------------------------

  ALTER TABLE "CMDBA"."SECRETARIA" ADD CONSTRAINT "SECRETARIA_EMAIL_UNV1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."SECRETARIA" ADD CONSTRAINT "SECRETARIA_RUT_UNV1" UNIQUE ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."SECRETARIA" ADD CONSTRAINT "SECRETARIA_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("CENTRO_MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("MATERNO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("PATERNO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."SECRETARIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALENDARIO_BASE
--------------------------------------------------------

  ALTER TABLE "CMDBA"."CALENDARIO_BASE" ADD CONSTRAINT "CALENDARIO_BASE_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."CALENDARIO_BASE" MODIFY ("CENTRO_MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CALENDARIO_BASE" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CALENDARIO_BASE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AGENDA
--------------------------------------------------------

  ALTER TABLE "CMDBA"."AGENDA" ADD CONSTRAINT "AGENDA_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."AGENDA" MODIFY ("MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."AGENDA" MODIFY ("HORA_TERMINO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."AGENDA" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."AGENDA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."AGENDA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPECIALIDAD
--------------------------------------------------------

  ALTER TABLE "CMDBA"."ESPECIALIDAD" ADD CONSTRAINT "ESPECIALIDAD_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."ESPECIALIDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."ESPECIALIDAD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "CMDBA"."DISPONIBILIDAD" ADD CONSTRAINT "DISPONIBILIDAD_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("DOMINGO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("SABADO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("VIERNES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("JUEVES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("MIERCOLES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("MARTES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("LUNES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("HORA_TERMINO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."DISPONIBILIDAD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICO
--------------------------------------------------------

  ALTER TABLE "CMDBA"."MEDICO" ADD CONSTRAINT "MEDICO_EMAIL_UNV1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."MEDICO" ADD CONSTRAINT "MEDICO_RUT_UNV1" UNIQUE ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."MEDICO" ADD CONSTRAINT "MEDICO_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("ESPECIALIDAD_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("CENTRO_MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("MINUTOS_ATENCION" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("MATERNO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("PATERNO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."MEDICO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CENTRO_MEDICO
--------------------------------------------------------

  ALTER TABLE "CMDBA"."CENTRO_MEDICO" ADD CONSTRAINT "CENTRO_MEDICO_EMAIL_UNV1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" ADD CONSTRAINT "CENTRO_MEDICO_RUT_UNV1" UNIQUE ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" ADD CONSTRAINT "CENTRO_MEDICO_PKV1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "CMDBA"."CENTRO_MEDICO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AGENDA
--------------------------------------------------------

  ALTER TABLE "CMDBA"."AGENDA" ADD CONSTRAINT "AGENDA_MEDICO_FKV1" FOREIGN KEY ("MEDICO_ID")
	  REFERENCES "CMDBA"."MEDICO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALENDARIO_BASE
--------------------------------------------------------

  ALTER TABLE "CMDBA"."CALENDARIO_BASE" ADD CONSTRAINT "C_BASE_C_MEDICO_FK" FOREIGN KEY ("CENTRO_MEDICO_ID")
	  REFERENCES "CMDBA"."CENTRO_MEDICO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "CMDBA"."DISPONIBILIDAD" ADD CONSTRAINT "DISPONIBILIDAD_MEDICO_FKV1" FOREIGN KEY ("MEDICO_ID")
	  REFERENCES "CMDBA"."MEDICO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICO
--------------------------------------------------------

  ALTER TABLE "CMDBA"."MEDICO" ADD CONSTRAINT "MEDICO_CENTRO_MEDICO_FKV1" FOREIGN KEY ("CENTRO_MEDICO_ID")
	  REFERENCES "CMDBA"."CENTRO_MEDICO" ("ID") ENABLE;
  ALTER TABLE "CMDBA"."MEDICO" ADD CONSTRAINT "MEDICO_ESPECIALIDAD_FKV1" FOREIGN KEY ("ESPECIALIDAD_ID")
	  REFERENCES "CMDBA"."ESPECIALIDAD" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECRETARIA
--------------------------------------------------------

  ALTER TABLE "CMDBA"."SECRETARIA" ADD CONSTRAINT "SECRETARIA_CENTRO_MEDICO_FKV1" FOREIGN KEY ("CENTRO_MEDICO_ID")
	  REFERENCES "CMDBA"."CENTRO_MEDICO" ("ID") ENABLE;
