-- Generado por Oracle SQL Developer Data Modeler 4.1.0.881
--   en:        2017-03-30 16:21:34 ART
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE CALENDARIO
  (
    ID_CAL         INTEGER NOT NULL ,
    MES            INTEGER NOT NULL ,
    HORARIO_ID_HOR INTEGER NOT NULL
  ) ;
ALTER TABLE CALENDARIO ADD CONSTRAINT CALENDARIO_PK PRIMARY KEY ( ID_CAL ) ;

CREATE TABLE CENTRO_MEDICO
  (
    ID_CME      INTEGER NOT NULL ,
    NOMBRE      VARCHAR2 (100) NOT NULL ,
    DIRECCION   VARCHAR2 (100) NOT NULL ,
    EMAIL       VARCHAR2 (100) NOT NULL ,
    TELEFONO    INTEGER NOT NULL ,
    HORA_APERT  DATE NOT NULL ,
    HORA_CIERRE DATE NOT NULL
  ) ;
ALTER TABLE CENTRO_MEDICO ADD CONSTRAINT CENTRO_MEDICO_PK PRIMARY KEY ( ID_CME ) ;

CREATE TABLE ERRORES
  (
    ID           INTEGER NOT NULL ,
    FECHA        DATE NOT NULL ,
    TABLA        VARCHAR2 (100) NOT NULL ,
    CODIGO_ERROR VARCHAR2 (20) NOT NULL ,
    DETALLE      VARCHAR2 (1024) NOT NULL
  ) ;
ALTER TABLE ERRORES ADD CONSTRAINT ERRORES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ESPECIALIDAD
  (
    ID_ESP INTEGER NOT NULL ,
    NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE ESPECIALIDAD ADD CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY ( ID_ESP ) ;

CREATE TABLE HORARIO
  (
    ID_HOR        INTEGER NOT NULL ,
    LUNES         SMALLINT NOT NULL ,
    MARTES        SMALLINT NOT NULL ,
    MIERCOLES     SMALLINT NOT NULL ,
    JUEVES        SMALLINT NOT NULL ,
    VIERNES       SMALLINT NOT NULL ,
    SABADO        SMALLINT NOT NULL ,
    DOMINGO       SMALLINT NOT NULL ,
    INICIO        DATE NOT NULL ,
    TERMINO       DATE NOT NULL ,
    MEDICO_ID_MED INTEGER NOT NULL
  ) ;
ALTER TABLE HORARIO ADD CONSTRAINT HORARIO_PK PRIMARY KEY ( ID_HOR ) ;

CREATE TABLE LOG_RESERVA
  (
    ID         INTEGER NOT NULL ,
    FECHA      VARCHAR2 (50) NOT NULL ,
    ESTADO     VARCHAR2 (50) NOT NULL ,
    ID_USUARIO INTEGER NOT NULL ,
    ID_RESERVA INTEGER NOT NULL
  ) ;
ALTER TABLE LOG_RESERVA ADD CONSTRAINT LOG_RESERVA_PK PRIMARY KEY ( ID ) ;

CREATE TABLE MEDICO
  (
    ID_MED               INTEGER NOT NULL ,
    NOMBRES              VARCHAR2 (100) NOT NULL ,
    PATERNO              VARCHAR2 (50) NOT NULL ,
    MATERNO              VARCHAR2 (50) NOT NULL ,
    CENTRO_MEDICO_ID_CME INTEGER NOT NULL ,
    ESPECIALIDAD_ID_ESP  INTEGER NOT NULL ,
    MED_MIN_AT           INTEGER NOT NULL ,
    MED_VALOR_AT         INTEGER NOT NULL ,
    USUARIO_ID_USU       INTEGER NOT NULL
  ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_PK PRIMARY KEY ( ID_MED ) ;

CREATE TABLE PACIENTE
  (
    ID_PACIENTE    INTEGER NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1) NOT NULL ,
    NOMBRES        VARCHAR2 (100) NOT NULL ,
    PATERNO        VARCHAR2 (50) NOT NULL ,
    MATERNO        VARCHAR2 (50) NOT NULL ,
    FNAC           DATE NOT NULL ,
    DIRECCION      VARCHAR2 (150) NOT NULL ,
    CELULAR        INTEGER ,
    TELEFONO       INTEGER ,
    USUARIO_ID_USU INTEGER NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( ID_PACIENTE ) ;

CREATE TABLE SECRETARIA
  (
    ID_SECRE       INTEGER NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1) NOT NULL ,
    NOMBRES        VARCHAR2 (100) NOT NULL ,
    PATERNO        VARCHAR2 (50) NOT NULL ,
    MATERNO        VARCHAR2 (50) NOT NULL ,
    FNAC           DATE NOT NULL ,
    DIRECCION      VARCHAR2 (150) NOT NULL ,
    CELULAR        INTEGER ,
    TELEFONO       INTEGER ,
    ESTADO         SMALLINT NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    USUARIO_ID_USU INTEGER NOT NULL
  ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PK PRIMARY KEY ( ID_SECRE ) ;

CREATE TABLE TIPO_USUARIO
  (
    ID_TUSU INTEGER NOT NULL ,
    NOMBRE  VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE TIPO_USUARIO ADD CONSTRAINT TIPO_USUARIO_PK PRIMARY KEY ( ID_TUSU ) ;

CREATE TABLE USUARIO
  (
    ID_USU               INTEGER NOT NULL ,
    USERNAME             VARCHAR2 (30) NOT NULL ,
    PASS                 VARCHAR2 (32) NOT NULL ,
    FREGISTRO            DATE NOT NULL ,
    ESTADO               SMALLINT NOT NULL ,
    TIPO_USUARIO_ID_TUSU INTEGER ,
    USU_EMAIL            VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( ID_USU ) ;

ALTER TABLE CALENDARIO ADD CONSTRAINT CALENDARIO_HORARIO_FK FOREIGN KEY ( HORARIO_ID_HOR ) REFERENCES HORARIO ( ID_HOR ) ;

ALTER TABLE HORARIO ADD CONSTRAINT HORARIO_MEDICO_FK FOREIGN KEY ( MEDICO_ID_MED ) REFERENCES MEDICO ( ID_MED ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_CENTRO_MEDICO_FK FOREIGN KEY ( CENTRO_MEDICO_ID_CME ) REFERENCES CENTRO_MEDICO ( ID_CME ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY ( ESPECIALIDAD_ID_ESP ) REFERENCES ESPECIALIDAD ( ID_ESP ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USU ) REFERENCES USUARIO ( ID_USU ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USU ) REFERENCES USUARIO ( ID_USU ) ;

ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USU ) REFERENCES USUARIO ( ID_USU ) ;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_TIPO_USUARIO_FK FOREIGN KEY ( TIPO_USUARIO_ID_TUSU ) REFERENCES TIPO_USUARIO ( ID_TUSU ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
