-- Generado por Oracle SQL Developer Data Modeler 4.1.0.881
--   en:        2017-03-27 14:32:31 ART
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE ATENCION CASCADE CONSTRAINTS ;

DROP TABLE CAJA CASCADE CONSTRAINTS ;

DROP TABLE CAJERO CASCADE CONSTRAINTS ;

DROP TABLE CALENDARIO CASCADE CONSTRAINTS ;

DROP TABLE CENTRO_MEDICO CASCADE CONSTRAINTS ;

DROP TABLE ERRORES CASCADE CONSTRAINTS ;

DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS ;

DROP TABLE FORMA_PAGO CASCADE CONSTRAINTS ;

DROP TABLE HORARIO CASCADE CONSTRAINTS ;

DROP TABLE LOG_RESERVA CASCADE CONSTRAINTS ;

DROP TABLE MEDICO CASCADE CONSTRAINTS ;

DROP TABLE PACIENTE CASCADE CONSTRAINTS ;

DROP TABLE PERSONAL CASCADE CONSTRAINTS ;

DROP TABLE PREVISION CASCADE CONSTRAINTS ;

DROP TABLE RECAUDACION CASCADE CONSTRAINTS ;

DROP TABLE RESERVA CASCADE CONSTRAINTS ;

DROP TABLE SECRETARIA CASCADE CONSTRAINTS ;

DROP TABLE TIPO_PAGO CASCADE CONSTRAINTS ;

DROP TABLE TIPO_RESERVA CASCADE CONSTRAINTS ;

DROP TABLE TIPO_USUARIO CASCADE CONSTRAINTS ;

DROP TABLE USUARIO CASCADE CONSTRAINTS ;

CREATE TABLE ATENCION
  (
    ATE_ID            INTEGER NOT NULL ,
    TIPO_PAGO_TPA_ID  INTEGER NOT NULL ,
    FORMA_PAGO_FPA_ID INTEGER NOT NULL ,
    CAJA_CAJ_ID       INTEGER NOT NULL
  ) ;
ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_PKv1 PRIMARY KEY ( ATE_ID ) ;

CREATE TABLE CAJA
  (
    CAJ_ID     INTEGER NOT NULL ,
    CAJ_NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE CAJA ADD CONSTRAINT CAJA_PKv1 PRIMARY KEY ( CAJ_ID ) ;

CREATE TABLE CAJERO
  (
    PER_ID      INTEGER NOT NULL ,
    CJR_ID      INTEGER NOT NULL ,
    CAJA_CAJ_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_PKv3 PRIMARY KEY ( PER_ID ) ;
ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_PKv5 UNIQUE ( CJR_ID ) ;

CREATE TABLE CALENDARIO
  (
    CAL_ID         INTEGER NOT NULL ,
    CAL_MES        INTEGER NOT NULL ,
    HORARIO_HOR_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CALENDARIO ADD CONSTRAINT CALENDARIO_PKv1 PRIMARY KEY ( CAL_ID ) ;

CREATE TABLE CENTRO_MEDICO
  (
    CME_ID          INTEGER NOT NULL ,
    CME_NOMBRE      VARCHAR2 (100) NOT NULL ,
    CME_DIRECCION   VARCHAR2 (100) NOT NULL ,
    CME_EMAIL       VARCHAR2 (100) NOT NULL ,
    CME_TELEFONO    INTEGER NOT NULL ,
    CME_HORA_APERT  DATE NOT NULL ,
    CME_HORA_CIERRE DATE NOT NULL
  ) ;
ALTER TABLE CENTRO_MEDICO ADD CONSTRAINT CENTRO_MEDICO_PKv1 PRIMARY KEY ( CME_ID ) ;

CREATE TABLE ERRORES
  (
    ID           INTEGER NOT NULL ,
    FECHA        DATE NOT NULL ,
    TABLA        VARCHAR2 (100) NOT NULL ,
    CODIGO_ERROR VARCHAR2 (20) NOT NULL ,
    DETALLE      VARCHAR2 (1024) NOT NULL
  ) ;
ALTER TABLE ERRORES ADD CONSTRAINT ERRORES_PKv1 PRIMARY KEY ( ID ) ;

CREATE TABLE ESPECIALIDAD
  (
    ESP_ID     INTEGER NOT NULL ,
    ESP_NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE ESPECIALIDAD ADD CONSTRAINT ESPECIALIDAD_PKv1 PRIMARY KEY ( ESP_ID ) ;

CREATE TABLE FORMA_PAGO
  (
    FPA_ID     INTEGER NOT NULL ,
    FPA_NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT FORMA_PAGO_PKv1 PRIMARY KEY ( FPA_ID ) ;

CREATE TABLE HORARIO
  (
    HOR_ID        INTEGER NOT NULL ,
    HOR_LUNES     SMALLINT NOT NULL ,
    HOR_MARTES    SMALLINT NOT NULL ,
    HOR_MIERCOLES SMALLINT NOT NULL ,
    HOR_JUEVES    SMALLINT NOT NULL ,
    HOR_VIERNES   SMALLINT NOT NULL ,
    HOR_SABADO    SMALLINT NOT NULL ,
    HOR_DOMINGO   SMALLINT NOT NULL ,
    HOR_INICIO    DATE NOT NULL ,
    HOR_TERMINO   DATE NOT NULL ,
    MEDICO_MED_ID INTEGER NOT NULL
  ) ;
ALTER TABLE HORARIO ADD CONSTRAINT HORARIO_PKv1 PRIMARY KEY ( HOR_ID ) ;

CREATE TABLE LOG_RESERVA
  (
    ID         INTEGER NOT NULL ,
    FECHA      VARCHAR2 (50) NOT NULL ,
    ESTADO     VARCHAR2 (50) NOT NULL ,
    ID_USUARIO INTEGER NOT NULL ,
    ID_RESERVA INTEGER NOT NULL
  ) ;
ALTER TABLE LOG_RESERVA ADD CONSTRAINT LOG_RESERVA_PKv1 PRIMARY KEY ( ID ) ;

CREATE TABLE MEDICO
  (
    MED_ID               INTEGER NOT NULL ,
    MED_NOMBRES          VARCHAR2 (100) NOT NULL ,
    MED_PATERNO          VARCHAR2 (50) NOT NULL ,
    MED_MATERNO          VARCHAR2 (50) NOT NULL ,
    CENTRO_MEDICO_CME_ID INTEGER NOT NULL ,
    ESPECIALIDAD_ESP_ID  INTEGER NOT NULL ,
    MED_MIN_AT           INTEGER NOT NULL ,
    MED_VALOR_AT         INTEGER NOT NULL ,
    USUARIO_USU_ID       INTEGER NOT NULL
  ) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_PKv1 PRIMARY KEY ( MED_ID ) ;

CREATE TABLE PACIENTE
  (
    PAC_ID           INTEGER NOT NULL ,
    PAC_RUT          INTEGER NOT NULL ,
    PAC_DV           VARCHAR2 (1) NOT NULL ,
    PAC_NOMBRES      VARCHAR2 (100) NOT NULL ,
    PAC_PATERNO      VARCHAR2 (50) NOT NULL ,
    PAC_MATERNO      VARCHAR2 (50) NOT NULL ,
    PAC_FNAC         DATE NOT NULL ,
    PAC_DIRECCION    VARCHAR2 (150) NOT NULL ,
    PAC_CELULAR      INTEGER ,
    PAC_TELEFONO     INTEGER ,
    PREVISION_PRE_ID INTEGER NOT NULL ,
    USUARIO_USU_ID   INTEGER NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PKv1 PRIMARY KEY ( PAC_ID ) ;

CREATE TABLE PERSONAL
  (
    PER_ID         INTEGER NOT NULL ,
    RUT            INTEGER NOT NULL ,
    DV             VARCHAR2 (1) NOT NULL ,
    NOMBRES        VARCHAR2 (100) NOT NULL ,
    PATERNO        VARCHAR2 (50) NOT NULL ,
    MATERNO        VARCHAR2 (50) NOT NULL ,
    FNAC           DATE NOT NULL ,
    DIRECCION      VARCHAR2 (150) NOT NULL ,
    CELULAR        INTEGER ,
    TELEFONO       INTEGER ,
    ESTADO         SMALLINT NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    USUARIO_USU_ID INTEGER NOT NULL
  ) ;
ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_PK PRIMARY KEY ( PER_ID ) ;

CREATE TABLE PREVISION
  (
    PRE_ID     INTEGER NOT NULL ,
    PRE_NOMBRE VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE PREVISION ADD CONSTRAINT PREVISION_PKv1 PRIMARY KEY ( PRE_ID ) ;

CREATE TABLE RECAUDACION
  (
    REC_ID          INTEGER NOT NULL ,
    ATENCION_ATE_ID INTEGER NOT NULL ,
    REC_PORCENTAJE FLOAT NOT NULL ,
    REC_TOTAL INTEGER NOT NULL
  ) ;
ALTER TABLE RECAUDACION ADD CONSTRAINT RECAUDACION_PKv1 PRIMARY KEY ( REC_ID ) ;

CREATE TABLE RESERVA
  (
    RES_ID              INTEGER NOT NULL ,
    RES_FECHA           DATE NOT NULL ,
    RES_HORA_INICIO     DATE NOT NULL ,
    RES_HORA_TERM       DATE NOT NULL ,
    MEDICO_MED_ID       INTEGER NOT NULL ,
    PACIENTE_PAC_ID     INTEGER NOT NULL ,
    TIPO_RESERVA_TRE_ID INTEGER NOT NULL ,
    RES_ESTADO          SMALLINT NOT NULL ,
    ATENCION_ATE_ID     INTEGER NOT NULL
  ) ;
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PKv1 PRIMARY KEY ( RES_ID ) ;

CREATE TABLE SECRETARIA
  (
    PER_ID INTEGER NOT NULL ,
    SEC_ID INTEGER NOT NULL
  ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PKv3 PRIMARY KEY ( PER_ID ) ;
ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PKv5 UNIQUE ( SEC_ID ) ;

CREATE TABLE TIPO_PAGO
  (
    TPA_ID     INTEGER NOT NULL ,
    TPA_NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE TIPO_PAGO ADD CONSTRAINT TIPO_PAGO_PKv1 PRIMARY KEY ( TPA_ID ) ;

CREATE TABLE TIPO_RESERVA
  (
    TRE_ID     INTEGER NOT NULL ,
    TRE_NOMBRE VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE TIPO_RESERVA ADD CONSTRAINT TIPO_RESERVA_PKv1 PRIMARY KEY ( TRE_ID ) ;

CREATE TABLE TIPO_USUARIO
  (
    TU_ID     INTEGER NOT NULL ,
    TU_NOMBRE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE TIPO_USUARIO ADD CONSTRAINT TIPO_USUARIO_PKv1 PRIMARY KEY ( TU_ID ) ;

CREATE TABLE USUARIO
  (
    USU_ID             INTEGER NOT NULL ,
    USU_USERNAME       VARCHAR2 (30) NOT NULL ,
    USU_PASS           VARCHAR2 (32) NOT NULL ,
    USU_ULTIMOPASS     VARCHAR2 (32) NOT NULL ,
    USU_FREGISTRO      DATE NOT NULL ,
    USU_ESTADO         SMALLINT NOT NULL ,
    TIPO_USUARIO_TU_ID INTEGER ,
    USU_EMAIL          VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PKv1 PRIMARY KEY ( USU_ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_CAJA_FKv1 FOREIGN KEY ( CAJA_CAJ_ID ) REFERENCES CAJA ( CAJ_ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_FORMA_PAGO_FKv1 FOREIGN KEY ( FORMA_PAGO_FPA_ID ) REFERENCES FORMA_PAGO ( FPA_ID ) ;

ALTER TABLE ATENCION ADD CONSTRAINT ATENCION_TIPO_PAGO_FKv1 FOREIGN KEY ( TIPO_PAGO_TPA_ID ) REFERENCES TIPO_PAGO ( TPA_ID ) ;

ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_CAJA_FKv1 FOREIGN KEY ( CAJA_CAJ_ID ) REFERENCES CAJA ( CAJ_ID ) ;

ALTER TABLE CAJERO ADD CONSTRAINT CAJERO_PERSONAL_FK FOREIGN KEY ( PER_ID ) REFERENCES PERSONAL ( PER_ID ) ;

ALTER TABLE CALENDARIO ADD CONSTRAINT CALENDARIO_HORARIO_FKv1 FOREIGN KEY ( HORARIO_HOR_ID ) REFERENCES HORARIO ( HOR_ID ) ;

ALTER TABLE HORARIO ADD CONSTRAINT HORARIO_MEDICO_FKv1 FOREIGN KEY ( MEDICO_MED_ID ) REFERENCES MEDICO ( MED_ID ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_CENTRO_MEDICO_FKv1 FOREIGN KEY ( CENTRO_MEDICO_CME_ID ) REFERENCES CENTRO_MEDICO ( CME_ID ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD_FKv1 FOREIGN KEY ( ESPECIALIDAD_ESP_ID ) REFERENCES ESPECIALIDAD ( ESP_ID ) ;

ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_USUARIO_FKv1 FOREIGN KEY ( USUARIO_USU_ID ) REFERENCES USUARIO ( USU_ID ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PREVISION_FKv1 FOREIGN KEY ( PREVISION_PRE_ID ) REFERENCES PREVISION ( PRE_ID ) ;

ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_USUARIO_FKv1 FOREIGN KEY ( USUARIO_USU_ID ) REFERENCES USUARIO ( USU_ID ) ;

ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_USUARIO_FKv1 FOREIGN KEY ( USUARIO_USU_ID ) REFERENCES USUARIO ( USU_ID ) ;

ALTER TABLE RECAUDACION ADD CONSTRAINT RECAUDACION_ATENCION_FKv1 FOREIGN KEY ( ATENCION_ATE_ID ) REFERENCES ATENCION ( ATE_ID ) ;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_ATENCION_FKv1 FOREIGN KEY ( ATENCION_ATE_ID ) REFERENCES ATENCION ( ATE_ID ) ;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_MEDICO_FKv1 FOREIGN KEY ( MEDICO_MED_ID ) REFERENCES MEDICO ( MED_ID ) ;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PACIENTE_FKv1 FOREIGN KEY ( PACIENTE_PAC_ID ) REFERENCES PACIENTE ( PAC_ID ) ;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_TIPO_RESERVA_FKv1 FOREIGN KEY ( TIPO_RESERVA_TRE_ID ) REFERENCES TIPO_RESERVA ( TRE_ID ) ;

ALTER TABLE SECRETARIA ADD CONSTRAINT SECRETARIA_PERSONAL_FKv1 FOREIGN KEY ( PER_ID ) REFERENCES PERSONAL ( PER_ID ) ;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_TIPO_USUARIO_FKv1 FOREIGN KEY ( TIPO_USUARIO_TU_ID ) REFERENCES TIPO_USUARIO ( TU_ID ) ;

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated
--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
